import { access, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = path.resolve(fileURLToPath(new URL("..", import.meta.url)));

const PORTABLE_FILES = [
  ["core/WORKFLOW.md", "docs/todokiso/WORKFLOW.md"],
  ["core/EXECUTION.md", "docs/todokiso/EXECUTION.md"],
  ["templates/impact-analysis.md", "docs/todokiso/templates/impact-analysis.md"],
  [
    "templates/detailed-design-work-packages.md",
    "docs/todokiso/templates/detailed-design-work-packages.md",
  ],
  ["templates/business-issue.md", "docs/todokiso/templates/business-issue.md"],
  [
    "templates/work-package-issue.md",
    "docs/todokiso/templates/work-package-issue.md",
  ],
  ["templates/pull-request.md", "docs/todokiso/templates/pull-request.md"],
];

async function exists(filePath) {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function readTextIfExists(filePath) {
  if (!(await exists(filePath))) {
    return null;
  }
  return readFile(filePath, "utf8");
}

async function readJsonIfExists(filePath) {
  const content = await readTextIfExists(filePath);
  if (content === null) {
    return null;
  }

  try {
    return JSON.parse(content);
  } catch {
    return null;
  }
}

async function detectPackageManager(targetDir, packageJson) {
  const declared = packageJson?.packageManager;
  if (typeof declared === "string") {
    const name = declared.split("@", 1)[0];
    if (["pnpm", "npm", "yarn", "bun"].includes(name)) {
      return name;
    }
  }

  const candidates = [
    ["pnpm-lock.yaml", "pnpm"],
    ["package-lock.json", "npm"],
    ["yarn.lock", "yarn"],
    ["bun.lock", "bun"],
    ["bun.lockb", "bun"],
  ];

  for (const [file, name] of candidates) {
    if (await exists(path.join(targetDir, file))) {
      return name;
    }
  }

  return null;
}

async function detectDirectories(targetDir) {
  const candidates = [
    "src",
    "app",
    "lib",
    "packages",
    "tests",
    "test",
    "docs",
    ".github",
  ];
  const found = [];

  for (const candidate of candidates) {
    if (await exists(path.join(targetDir, candidate))) {
      found.push(candidate);
    }
  }

  return found;
}

async function detectCi(targetDir) {
  const workflows = path.join(targetDir, ".github", "workflows");
  if (!(await exists(workflows))) {
    return [];
  }

  try {
    return (await readdir(workflows))
      .filter((name) => /\.ya?ml$/i.test(name))
      .sort()
      .map((name) => `.github/workflows/${name}`);
  } catch {
    return [];
  }
}

export async function inspectRepository(targetDir) {
  const packageJson = await readJsonIfExists(path.join(targetDir, "package.json"));
  const packageManager = await detectPackageManager(targetDir, packageJson);
  const directories = await detectDirectories(targetDir);
  const ciWorkflows = await detectCi(targetDir);

  return {
    packageJson,
    packageManager,
    directories,
    ciWorkflows,
  };
}

function installCommand(packageManager) {
  switch (packageManager) {
    case "pnpm":
      return "pnpm install";
    case "yarn":
      return "yarn install";
    case "bun":
      return "bun install";
    case "npm":
      return "npm install";
    default:
      return "TODO";
  }
}

function scriptCommand(packageManager, script) {
  if (!script) {
    return "TODO";
  }

  switch (packageManager) {
    case "pnpm":
      return `pnpm ${script}`;
    case "yarn":
      return `yarn ${script}`;
    case "bun":
      return `bun run ${script}`;
    case "npm":
      return `npm run ${script}`;
    default:
      return `TODO: run ${script}`;
  }
}

function commandForScripts(facts, names) {
  const scripts = facts.packageJson?.scripts ?? {};
  const script = names.find((name) => scripts[name]);
  return scriptCommand(facts.packageManager, script);
}

function dependencyList(packageJson) {
  if (!packageJson) {
    return [];
  }

  return [
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {}),
  ].sort();
}

export function renderRepositoryProfile(facts) {
  const pkg = facts.packageJson;
  const purpose = pkg?.description || "TODO: describe the repository purpose.";
  const runtime = pkg?.engines?.node
    ? `Node.js ${pkg.engines.node}`
    : "TODO: identify the runtime / toolchain.";
  const dependencies = dependencyList(pkg);
  const directories =
    facts.directories.length > 0
      ? facts.directories.map((dir) => `- \`${dir}/\``).join("\n")
      : "- TODO: identify important directories.";
  const ci =
    facts.ciWorkflows.length > 0
      ? facts.ciWorkflows.map((file) => `- \`${file}\``).join("\n")
      : "- TODO: identify CI workflows.";

  return `# Repository Profile

> Generated by \`todokiso init\`. This is a draft: review every TODO / Unknown before using it as an Executor contract.

## Project

### Purpose
${purpose}

### Key user / system outcomes
- TODO / Unknown

## Architecture

### Stack
- Runtime: ${runtime}
- Package manager: ${facts.packageManager ?? "TODO / Unknown"}
${dependencies.length > 0 ? `- Detected packages: ${dependencies.join(", ")}` : "- Detected packages: TODO / Unknown"}

### Important directories
${directories}

### Main data / control flow
- TODO / Unknown

### Architectural invariants
- TODO / Unknown

### ADR / design documentation
- TODO / Unknown

## Development

### Setup
- \`${installCommand(facts.packageManager)}\`

### Standard commands

| Purpose | Command |
| --- | --- |
| Install | \`${installCommand(facts.packageManager)}\` |
| Dev | \`${commandForScripts(facts, ["dev", "start"])}\` |
| Lint | \`${commandForScripts(facts, ["lint"])}\` |
| Typecheck | \`${commandForScripts(facts, ["typecheck", "type-check"])}\` |
| Unit / integration test | \`${commandForScripts(facts, ["test"])}\` |
| Build | \`${commandForScripts(facts, ["build"])}\` |
| E2E | \`${commandForScripts(facts, ["test:e2e", "e2e"])}\` |

### Coding conventions
- TODO / Unknown

## Testing

### Test layers
- TODO / Unknown

### When tests are required
- TODO / Unknown

### Environment-specific verification
- TODO / Unknown

## CI / Deployment

### Detected CI
${ci}

### Required checks
- TODO / Unknown

### Preview / staging
- TODO / Unknown

### Release / production
- TODO / Unknown

### Rollback
- TODO / Unknown

## Repository Guardrails

- Security / secrets: TODO / Unknown
- Data compatibility: TODO / Unknown
- Prohibited changes: TODO / Unknown
- Scope discipline: TODO / Unknown
- Generated / temporary files: TODO / Unknown

## todokiso Role Mapping

| Role | Current actor |
| --- | --- |
| Decision Owner | TODO / Unknown |
| Planner | TODO / Unknown |
| Executor | TODO / Unknown |
| Reviewer | TODO / Unknown |

## Approval Ownership

- Gate 1 — Go / No-Go: TODO / Unknown
- Gate 2 — Ready for Implementation: TODO / Unknown
- Merge / release authority: TODO / Unknown

## Local integration notes

Document labels, automated triggers, vendor-specific permissions, agent setup, snapshots, and other tool-specific mechanics here rather than in todokiso core.
`;
}

export function renderSource(
  version,
  date = new Date().toISOString().slice(0, 10),
  sourceRevision = null,
) {
  const sourceLine = sourceRevision
    ? `- Source revision: \`${sourceRevision}\`\n`
    : "";

  return `# todokiso source

- Upstream: https://github.com/acorn181/todokiso
- Package revision: todokiso@${version}
${sourceLine}- Bootstrapped: ${date}

## Local adaptations

- Repository-specific commands and policy live in \`../REPOSITORY_PROFILE.md\`.
- If core semantics are adapted locally, document the reason here.

## Upgrade policy

Upgrade todokiso explicitly: compare the current vendored snapshot with a chosen newer release, review semantic changes, update this file, and merge the change through a dedicated process PR.
`;
}

async function plannedFile(targetDir, relativePath, content) {
  const absolutePath = path.join(targetDir, relativePath);
  const existing = await readTextIfExists(absolutePath);

  if (existing === null) {
    return { status: "create", relativePath, absolutePath, content };
  }

  if (existing === content) {
    return { status: "skip", relativePath, absolutePath, content };
  }

  return { status: "conflict", relativePath, absolutePath, content };
}

export async function createBootstrapPlan(
  targetDir,
  {
    assetRoot = PACKAGE_ROOT,
    version = "0.1.0",
    date = new Date().toISOString().slice(0, 10),
    sourceRevision = null,
  } = {},
) {
  const resolvedTarget = path.resolve(targetDir);
  const facts = await inspectRepository(resolvedTarget);
  const entries = [];

  for (const [source, destination] of PORTABLE_FILES) {
    const content = await readFile(path.join(assetRoot, source), "utf8");
    entries.push(await plannedFile(resolvedTarget, destination, content));
  }

  entries.push(
    await plannedFile(
      resolvedTarget,
      "docs/todokiso/SOURCE.md",
      renderSource(version, date, sourceRevision),
    ),
  );
  entries.push(
    await plannedFile(
      resolvedTarget,
      "docs/REPOSITORY_PROFILE.md",
      renderRepositoryProfile(facts),
    ),
  );

  return {
    targetDir: resolvedTarget,
    facts,
    entries,
  };
}

export async function applyBootstrapPlan(plan) {
  const conflicts = plan.entries.filter((entry) => entry.status === "conflict");
  if (conflicts.length > 0) {
    throw new Error(
      `refusing to overwrite existing files: ${conflicts
        .map((entry) => entry.relativePath)
        .join(", ")}`,
    );
  }

  for (const entry of plan.entries) {
    if (entry.status !== "create") {
      continue;
    }

    await mkdir(path.dirname(entry.absolutePath), { recursive: true });
    await writeFile(entry.absolutePath, entry.content, "utf8");
  }
}
